import Testing
import Foundation
@testable import Scout

// A realistic multi-proposal file: intro + how-it-works (must be ignored),
// then four proposals spanning every awaiting/resolved status, including a
// fenced ```bash block in the first body.
private let proposalsFixture = """
# Dreaming Proposals

Proposals for changes to SKILL.md, generated by dreaming feedback processing runs.

## How It Works

1. Dreaming identifies improvements
2. Adam reviews and approves

---

## Proposals

### P-2026-06-13-01 — Add a risk-scoped PR re-resolution step

**Status:** Proposed (awaiting Adam approval)
**Source:** dreaming 2026-06-13 feedback on [[#BB290]].

**Problem.** SKILL.md anchored on one known PR number.

**Proposed SKILL.md change** (in the cross-check section):

```bash
gh pr list --repo <repo> --state all --search "<keyword>"
```

Treat any OPEN PR whose title carries the risk id as the live fix.

### P-2026-06-10-02 — Tighten the budget gate

**Status:** Pending (auto-apply after 2026-06-13)

**Trigger:** repeated budget overruns.

### 2026-06-01 — An already-applied tweak

**Status:** Applied — 2026-06-02

Body of the applied proposal.

### P-2026-05-20-09 — A rejected idea

**Status:** Rejected

This one was turned down.
"""

@Suite("ProposalsParser")
struct ProposalsParserTests {

    @Test func parsesAllProposalsIgnoringIntroAndHowItWorks() {
        let proposals = ProposalsParser.parse(text: proposalsFixture)
        #expect(proposals.count == 4)
        // The `#`/`##` headings (title, How It Works, Proposals) are not
        // mistaken for proposals.
        #expect(proposals.allSatisfy { $0.headingLine.hasPrefix("### ") })
    }

    @Test func splitsHeadingIntoCodeAndTitle() {
        let proposals = ProposalsParser.parse(text: proposalsFixture)
        #expect(proposals[0].code == "P-2026-06-13-01")
        #expect(proposals[0].title == "Add a risk-scoped PR re-resolution step")
        // Template-style heading where the code is a bare date.
        #expect(proposals[2].code == "2026-06-01")
        #expect(proposals[2].title == "An already-applied tweak")
    }

    @Test func classifiesEachStatus() {
        let proposals = ProposalsParser.parse(text: proposalsFixture)
        #expect(proposals[0].status == .proposed)
        #expect(proposals[1].status == .pending(autoApplyDate: "2026-06-13"))
        #expect(proposals[2].status == .applied(date: "2026-06-02"))
        #expect(proposals[3].status == .rejected)
    }

    @Test func awaitingDecisionMatchesBadgeSemantics() {
        let proposals = ProposalsParser.parse(text: proposalsFixture)
        let awaiting = proposals.filter(\.isAwaitingDecision)
        // Proposed + Pending are awaiting; Applied + Rejected are resolved.
        #expect(awaiting.count == 2)
        #expect(awaiting.map(\.code) == ["P-2026-06-13-01", "P-2026-06-10-02"])
    }

    @Test func bodyExcludesStatusLineButKeepsEverythingElse() {
        let proposals = ProposalsParser.parse(text: proposalsFixture)
        let body = proposals[0].bodyMarkdown
        #expect(!body.contains("**Status:**"))
        #expect(body.contains("**Problem.**"))
        #expect(body.contains("gh pr list --repo"))
        #expect(body.contains("**Source:**"))
    }

    @Test func bodyBlocksLiftOutTheCodeFence() {
        let proposals = ProposalsParser.parse(text: proposalsFixture)
        let blocks = proposals[0].bodyBlocks
        let codeBlocks = blocks.compactMap { block -> String? in
            if case .code(_, let code) = block { return code } else { return nil }
        }
        #expect(codeBlocks.count == 1)
        #expect(codeBlocks.first == #"gh pr list --repo <repo> --state all --search "<keyword>""#)
        // And there is prose both before and after the code.
        #expect(blocks.first.map { if case .prose = $0 { return true } else { return false } } == true)
        #expect(blocks.last.map { if case .prose = $0 { return true } else { return false } } == true)
    }

    @Test func emptyTextYieldsNoProposals() {
        #expect(ProposalsParser.parse(text: "").isEmpty)
        #expect(ProposalsParser.parse(text: "# Just a title\n\nsome prose").isEmpty)
    }
}
