import Foundation
import Combine
import OSLog
import SwiftUI

/// Loads `.scout-logs/connector-calls-*.jsonl` and `connector-alerts.log`
/// from the given logs directory and publishes:
/// 1. A `ConnectorHealthMatrix` (connectors × recent sessions).
/// 2. `activeAlerts`: non-acked `ConnectorAlert`s from the log.
///
/// The connector roster (`defaultConnectors`) is sourced from
/// `connectors.snapshot.json`, the JSON projection of scout-plugin's
/// `connectors.yaml` (Plan 4 Task 8). The snapshot is generated by
/// `scoutctl connectors snapshot` and lives canonically at
/// `~/scout-plugin/engine/scout/connectors.snapshot.json`. When the snapshot
/// can't be loaded, we fall back to a hardcoded list AND emit a noisy
/// log/banner so the operator knows to regenerate.
///
/// Shell scripts remain the source of truth for *which* alerts should fire
/// (`connector-health-report.sh` owns the 14-day sustained-state logic).
/// This service does not re-implement that logic — it only reads and
/// renders.
@MainActor
final class ConnectorHealthService: ObservableObject {
    @Published private(set) var matrix: ConnectorHealthMatrix
    @Published private(set) var activeAlerts: [ConnectorAlert] = []
    /// Set to a non-nil string when the snapshot couldn't be loaded and we're
    /// running on the hardcoded fallback list. Surface this in the UI so the
    /// operator notices that the cross-repo sync slipped.
    @Published private(set) var rosterFallbackReason: String? = nil

    private let logsDirectory: URL
    private let ackStore: ConnectorAckStore
    private let fileEvents: any FileSystemEventSource
    private let connectors: [String]
    private var watchTask: Task<Void, Never>?

    private static let log = Logger(subsystem: "com.scout.Scout", category: "ConnectorHealth")

    init(
        logsDirectory: URL,
        ackStoreURL: URL,
        fileEvents: any FileSystemEventSource,
        connectors: [String]? = nil,
        snapshotURL: URL? = nil
    ) {
        self.logsDirectory = logsDirectory
        self.ackStore = ConnectorAckStore(fileURL: ackStoreURL)
        self.fileEvents = fileEvents

        if let connectors {
            // Explicit override — primarily for tests.
            self.connectors = connectors
            self.rosterFallbackReason = nil
        } else {
            let url = snapshotURL ?? Self.defaultSnapshotURL
            switch Self.loadRoster(from: url) {
            case .success(let keys):
                self.connectors = keys
                self.rosterFallbackReason = nil
            case .failure(let err):
                let msg = "Connector roster snapshot missing — run `scoutctl connectors snapshot` in scout-plugin. (\(err.message))"
                Self.log.error("\(msg, privacy: .public)")
                self.connectors = Self.fallbackConnectors
                self.rosterFallbackReason = msg
            }
        }

        self.matrix = ConnectorHealthMatrix(calls: [], connectors: self.connectors)
    }

    // MARK: - Roster loading

    /// Production default: the canonical snapshot in scout-plugin's git repo
    /// at `~/scout-plugin/engine/scout/connectors.snapshot.json`. v0.4 is a
    /// personal tool — the path assumes scout-plugin is checked out alongside
    /// scout-app on the dev machine. Distributed builds will need a bundled
    /// resource path; tracked in BACKLOG.
    nonisolated static var defaultSnapshotURL: URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("scout-plugin/engine/scout/connectors.snapshot.json")
    }

    /// Shape mirroring `connectors.snapshot.json` v1.
    private struct SnapshotFile: Decodable {
        struct Entry: Decodable {
            let key: String
            let display_name: String
            let tier: String
        }
        let schema_version: Int
        let generated_from: String
        let connectors: [Entry]
    }

    /// Failure reason for snapshot loading. Carries a human-readable message
    /// for the operator banner (and logs).
    struct RosterLoadError: Error {
        let message: String
    }

    /// Load the connector roster from a snapshot URL. Returns the array of
    /// canonical keys on success, or a `RosterLoadError` with a human-readable
    /// reason on failure.
    nonisolated static func loadRoster(from url: URL) -> Result<[String], RosterLoadError> {
        guard FileManager.default.fileExists(atPath: url.path) else {
            return .failure(RosterLoadError(message: "snapshot not found at \(url.path)"))
        }
        do {
            let data = try Data(contentsOf: url)
            let parsed = try JSONDecoder().decode(SnapshotFile.self, from: data)
            guard parsed.schema_version == 1 else {
                return .failure(RosterLoadError(message: "unsupported snapshot schema_version=\(parsed.schema_version)"))
            }
            let keys = parsed.connectors.map { $0.key }
            guard !keys.isEmpty else {
                return .failure(RosterLoadError(message: "snapshot contained zero connectors"))
            }
            return .success(keys)
        } catch {
            return .failure(RosterLoadError(message: "failed to decode \(url.lastPathComponent): \(error)"))
        }
    }

    /// Hardcoded fallback used when the snapshot can't be read.
    /// Updated 2026-04-28 (Plan 4 Task 8) to use the canonical YAML keys
    /// (`mcp:claude_ai_Slack`, `mcp:claude_ai_Linear`) — the previous values
    /// (`mcp:plugin_slack_slack`, `mcp:plugin_linear_linear`) never matched
    /// what `connector_health_report.sh` actually emitted, so the rail card
    /// silently showed those rows as dark even when the connectors were fine.
    /// The fallback now includes WhatsApp + Telegram (10 connectors) to
    /// match the YAML.
    nonisolated static let fallbackConnectors: [String] = [
        "mcp:claude_ai_Slack",
        "mcp:claude_ai_Linear",
        "mcp:claude_ai_Gmail",
        "mcp:claude_ai_Google_Calendar",
        "mcp:claude_ai_Granola",
        "mcp:claude_ai_Google_Drive",
        "github",
        "mcp:claude-in-chrome",
        "mcp:whatsapp-mcp",
        "notify:telegram"
    ]

    /// Public default — loads from the canonical snapshot URL. Returns the
    /// fallback list if the snapshot is missing. Used by callers that want a
    /// roster without instantiating the full service.
    nonisolated static var defaultConnectors: [String] {
        switch loadRoster(from: defaultSnapshotURL) {
        case .success(let keys):
            return keys
        case .failure:
            return fallbackConnectors
        }
    }

    func loadInitial() async throws {
        await refresh()
        startWatching()
    }

    func acknowledge(fingerprint: String) {
        ackStore.ack(fingerprint: fingerprint)
        recomputeActiveAlerts(all: allAlertsFromLog())
    }

    // MARK: - Internals

    private func refresh() async {
        // 1. Matrix from all connector-calls-*.jsonl in logsDirectory within 14d window.
        let calls = await loadCallsWithinWindow()
        matrix = ConnectorHealthMatrix(calls: calls, connectors: connectors)
        // 2. Alerts from connector-alerts.log.
        let all = allAlertsFromLog()
        recomputeActiveAlerts(all: all)
        // 3. GC ack store against the live fingerprint set.
        ackStore.gc(active: Set(all.map(\.fingerprint)))
    }

    private func allAlertsFromLog() -> [ConnectorAlert] {
        let url = logsDirectory.appendingPathComponent("connector-alerts.log")
        return ConnectorAlert.parseFile(at: url)
    }

    private func recomputeActiveAlerts(all: [ConnectorAlert]) {
        // Deduplicate: keep latest ts per (connector, level).
        var latest: [String: ConnectorAlert] = [:]
        for a in all {
            let key = "\(a.connector)|\(a.level.rawValue)"
            if let existing = latest[key], existing.ts >= a.ts { continue }
            latest[key] = a
        }
        activeAlerts = latest.values
            .filter { !ackStore.isAcked($0.fingerprint) }
            .sorted { $0.ts > $1.ts }
    }

    private func loadCallsWithinWindow() async -> [ConnectorCall] {
        let fm = FileManager.default
        guard let entries = try? fm.contentsOfDirectory(
            at: logsDirectory,
            includingPropertiesForKeys: nil,
            options: [.skipsHiddenFiles]
        ) else { return [] }
        let jsonlURLs = entries.filter {
            let name = $0.lastPathComponent
            return name.hasPrefix("connector-calls-") && name.hasSuffix(".jsonl")
        }
        let windowStart = Date().addingTimeInterval(-14 * 24 * 3600)
        return await Task.detached { () -> [ConnectorCall] in
            var out: [ConnectorCall] = []
            for url in jsonlURLs {
                out.append(contentsOf: ConnectorCall.parseFile(at: url)
                    .filter { $0.ts >= windowStart })
            }
            return out
        }.value
    }

    private func startWatching() {
        watchTask?.cancel()
        watchTask = Task { [weak self] in
            guard let self else { return }
            for await event in self.fileEvents.events(for: self.logsDirectory) {
                let name = event.url.lastPathComponent
                let relevant = name.hasPrefix("connector-calls-")
                    || name == "connector-alerts.log"
                if relevant { await self.refresh() }
            }
        }
    }
}
